### ISSUE TITLE
У вас возникла идея

### ISSUE THREAD

**Issue by 23-yo-designer-from-san-francisco** [LaHainee/RK6_Internet_technologies#2]
Виталь) у Вас в репозитории находится Ваша мысль (идея), но Вам бы стоило ее озвучить
![IMG_20220115_202208_359-01](https://user-images.githubusercontent.com/42890090/149631343-aad68733-659c-4494-a08f-b3bede6d1c3f.jpeg)

**Comment by LaHainee** [comment]
Идея кикнуть Леонида Беляева и взять /kocenko в команду
